### ISSUE TITLE
only part of screen adjustments are done after scr_dump + scr_restore

### ISSUE THREAD

**Issue by GitMensch** [Bill-Gray/PDCursesMod#320] opened 2024-06-07 16:10 UTC
The first time the process display + getch + scr_dump + adjustments + getch + scr_restore + refresh works fine, the second time the adjustments are only shown in the oart that was explicit adjusted (while curses buffers still contain the right data).

![1st call](https://github.com/Bill-Gray/PDCursesMod/assets/6699539/7a47d95d-4dac-4f90-bf05-42306683072d)
![2nd call](https://github.com/Bill-Gray/PDCursesMod/assets/6699539/15844221-615a-4701-95fd-e2f5f288fe4c)

As a video (400KB each): compare ![ncurses](https://github.com/Bill-Gray/PDCursesMod/assets/6699539/a9d64da0-9ba0-466d-be11-90d327bea2c6) with ![wincon](https://github.com/Bill-Gray/PDCursesMod/assets/6699539/09e0576b-389e-48cd-8ece-95fbc8af52e6)

Curses buffers shown in GDB
![cmd_6pzfmWuLW8](https://github.com/Bill-Gray/PDCursesMod/assets/6699539/7c71db97-6a7e-498f-8e40-2341ce1a68ed)

----------------------

This was tested and be the case at least on Windows for VT, WinGUI, wincon.
This issue is to track what was already checked to have the most important parts of the correspondence here for reference.

Note that this is the upstream bug for [GnuCOBOL bug 646](https://sourceforge.net/p/gnucobol/bugs/946/).

----------------------

Analysis by @Bill-Gray with an (adjusted test program):

> What I'll probably need is a small demo example.  Fortunately,  I think we have one.
>
> The attached is a slightly modified version of your example. [...]
> In that case,  scr_restore() does not appear to result in an update at the following getch().  Nothing happens until the following mvprintw() and its subsequent getch().
>
> I think I've found the problem (and a solution).  See the following comment :
> https://github.com/Bill-Gray/PDCursesMod/blob/c0a3c2c0d3cc8d4239c49605835654e276f93b96/pdcurses/scr_dump.c#L33-L42
>
> It seems to me that,  in the absence of a `newscr`,  we should be restoring to `stdscr`.
> I modified [line 304 of pdcurses/scr_dump.c](https://github.com/Bill-Gray/PDCursesMod/blob/c0a3c2c0d3cc8d4239c49605835654e276f93b96/pdcurses/scr_dump.c#L304)
> ```diff
> -            int result = overwrite(replacement, curscr);
> +            int result = overwrite(replacement, stdscr);
> ```
> (i.e.,  replace `cur` with `std`) and all appears to be well.
>
> As best I can tell,  this really does fix the problem.  But I find this to be something of a head-scratcher, and have not committed the change yet.

[scrtest2.c.](https://github.com/user-attachments/files/15742096/scrtest2.c.txt)

This 3-byte change was later tested to actually fix the issue.

**Comment by Bill-Gray** [comment] 2024-06-08 01:34
Further on this : I've made a [simplified `scrtest.c`](https://github.com/user-attachments/files/15746024/scrtest.c.txt) to illustrate the problem more concisely.  Two things of note : 

- The behavior is the same in ncurses,  PDCurses,  and PDCursesMod.  I am increasingly of the opinion that this is the intended behavior.  As noted above,  `pdcurses/scr_dump.c`  is quite clear that the restoring to `curscr` is intentional,  and we now see ncurses doing something similar.
-  It appears that if you want to actually see the effects of `scr_restore()`,  you have to call `refresh()`.  The revised test code will do that if `scrtest` is provided with a command-line argument.  Supply an argument,  and the test program works.  Omit it,  and it doesn't.

So... please ignore my comment above about making the three-byte change.   Just make sure to call `refresh()` after calling `scr_restore()`.  Doing so fixes the issue on all platforms,  not just PDCursesMod.  (If you find a contrary case,  please re-open.)

Also,  note the comment in the file about `scr_dump()` : it works from what's actually on the screen,  so you need to call `refresh()` _before_ calling `scr_dump()` if you want as-yet-undrawn changes to end up in the screen dump file.

I'm closing this as "correct behavior that confused us for a bit,  not a bug".

**Closed by Bill-Gray** 2024-06-08 01:34 UTC

**Comment by GitMensch** [comment] 2024-06-08 09:13
Hm, the original test code does have the `refresh()` after `scr_restore()`- see the referenced GnuCOBOL bug.
I guess a run with `set_trace(1)` will help.
