### ISSUE TITLE
when using pdcurses-wingui.dll with commit 3719+ attempt to reference invalid memory address (signal)

### ISSUE THREAD

**Issue by chuck-haatvedt** [Bill-Gray/PDCursesMod#280] opened 2023-02-19 23:16 UTC
Bill,

I was doing some testing of an issue reported in GNUCOBOL using pdcurses-wincon.dll from the current trunk source. So at the request of Simon, I swiched to try pdcurses-wingui.dll and it crashed with the "attempt to reference invalid memory address (signal)" error.  Note that have not confirmed any error in the wincon version,  we are still diagnosing some character blinking behavior...    The issue is the invalid memory address in WINGUI.

So I started building PDCURSESMOD with earlier commits until I found which commit introduced the bug...   it is 3719.

here is the comment I see in the log in SVN

Port #45, #83 to current master branch.

Revision: 3719
Author: casey.langen
Date: Friday, December 30, 2022 4:41:45 PM
Message:
Port #45, #83 to current master branch.

----
Modified : /trunk/wingui/pdcdisp.c
Modified : /trunk/wingui/pdcscrn.c

**Comment by Bill-Gray** [comment] 2023-03-05 03:12
Hi Chuck - looks as if that's the fix to make the WinGUI port HiDPI-aware.  I assume the crashes occur at startup,  and in any PDCursesMod program?  Do they occur on one fork of Windows but not others (say,  on Win7 but not later versions)?

Anyone else seeing this error?

**Comment by RedSpah** [comment] 2023-03-18 20:55
I can chime in and say that I'm seeing this error as well. The entire WinGUI port appears to be currently broken.

Steps to reproduce:

* Clone the repository
* With a Developer Command Prompt for Visual Studio (issue happened both on VS 2017 and VS 2022), navigate to PDCursesMod/wingui
* run `nmake -f Makefile.vc testcurs.exe`
* Attempt to run the `testcurs.exe` demo

The observed result is it crashing immediately on startup.

**Comment by RedSpah** [comment] 2023-03-18 20:58
In addition, just tested this again with the commit just before the "Port #45 and #83 to current master branch." one, and it worked as expected then.

**Comment by Bill-Gray** [comment] 2023-03-19 02:59
@RedSpah @chuck-haatvedt  - I assume you both have high-DPI displays?  Also,  on what fork of Windows (Win11, Win10,  Win7,  etc.) is this happening?  And is it a 32-bit or 64-bit version?

Looking at @clangen 's code,  it all seems properly error-checked to me (nothing along the lines of "load this DLL,  assume you loaded it,  then call a function without checking to see if it's in the library").  However,  I do get warnings with MinGW-64.  For a 32-bit build : 
```c
../wingui/pdcscrn.c: In function ‘PDC_scr_open’:
../wingui/pdcscrn.c:2232:42: warning: cast between incompatible function types from ‘FARPROC’ to ‘HRESULT * (*)(int)’ {aka ‘long int * (*)(int)’} [-Wcast-function-type]
 2232 |         set_process_dpi_awareness_func = (set_process_dpi_awareness_t)GetProcAddress(shcoredll, "SetProcessDpiAwareness");
```
   And for a 64-bit build : 
```c
../wingui/pdcscrn.c: In function ‘PDC_scr_open’:
../wingui/pdcscrn.c:2232:42: warning: cast between incompatible function types from ‘FARPROC’ {aka ‘long long int (*)()’} to ‘HRESULT * (*)(int)’ {aka ‘long int * (*)(int)’} [-Wcast-function-type]
 2232 |         set_process_dpi_awareness_func = (set_process_dpi_awareness_t)GetProcAddress(shcoredll, "SetProcessDpiAwareness");
```
None of this is a problem on my systems,  because they lack the `SetProcessDpiAwareness()` function.  So we never actually try to call it.  My guess is that this code works on systems that _do_ have it,  but only 32-bit or 64-bit ones (or it may be you can compile a 32-bit program and have it work on all systems,  but a 64-bit version will fail.)

**Comment by GitMensch** [comment] 2023-03-20 08:34
I've did the following with a clean checkout:

```sh
# using msys2 provided mingw64 environmnt
cd wingui
make testcurs.exe
testcurs.exe  # no abort
make clean
```

```cmd
rem using VC2019 x64 command prompt
cd wingui
nmake -f Makefile.vc testcurs.exe
testcurs.exe  # no abort
```

I both cases an added debug code shows that the `SetProcessDpiAwareness` function is available (test system running on older Win11).

**Comment by GitMensch** [comment] 2023-03-20 09:18
Note @Bill-Gray @clangen I'm a bit confused about the use of` (int)2`, because of the msdn docs for https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-setprocessdpiawareness point to https://learn.microsoft.com/en-us/windows/win32/hidpi/dpi-awareness-context which documents

```c
#define DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE    ((DPI_AWARENESS_CONTEXT)-3)
```

**Comment by clangen** [comment] 2023-03-25 08:27
sorry i've been on jury duty... `FARPROC` -- bad calling convention corrupting the stack or heap?

**Comment by chuck-haatvedt** [comment] 2023-04-06 20:59
Has a fix for this issue been identified ?

if so, has it been committed such that we can now use the current build ?   

it would be nice to get this included in the next release.

**Comment by Bill-Gray** [comment] 2023-04-07 01:02
I've been simultaneously busy and (recently) sick.  Hasn't left much time,  I'm afraid... I've hopes of that changing in a bit,  but appreciate the efforts of everybody else in my absence.

Just based on the question about the use of 2 or -3,  I'd suggest editing `wingui/pdcscrn.c`,  going to line 2230,  and changing
```c
   static int ADJUST_DPI_PER_MONITOR = 2;
```
to read
```c
   static int ADJUST_DPI_PER_MONITOR = -3;
```
and see what happens.  I remain unable to replicate the problem and really don't know what's going on here.  But if you try that and it suddenly works properly,  I'd say we have a fix.

**Comment by chuck-haatvedt** [comment] 2023-04-07 23:17
I adjusted the line mentioned above and it did not make any difference

F:\AA-minGW32-static>copy D:\msys64\home\spcwh2\x32\pdcurses-trunk\wingui\pdcurses.dll *
Overwrite pdcurses.dll? (Yes/No/All): y
        1 file(s) copied.

F:\AA-minGW32-static>colors

attempt to reference invalid memory address (signal)


F:\AA-minGW32-static>dir pd*.dll
 Volume in drive F is Win-F
 Volume Serial Number is 900F-A64F

 Directory of F:\AA-minGW32-static

02/19/2023  02:16 PM           568,623 pdcurses-wincon.dll
02/19/2023  02:16 PM           588,550 pdcurses-wingui.dll
04/07/2023  06:06 PM           563,114 pdcurses.dll
               3 File(s)      1,720,287 bytes
               0 Dir(s)  177,361,580,032 bytes free

**Comment by chuck-haatvedt** [comment] 2023-04-08 00:09
I did a Google search and found the following...  

note that return value is -2147024809 is  0x80070057   

# Attempt to set the current process as DPI aware.  If sucessful, this will
#  ensure that the resolution is reported properly when DPI scaling is on.
#
# Note: Dragon itself sets the awareness to PROCESS_SYSTEM_DPI_AWARE, which
#  provides awareness of the DPI when the application starts, but not when
#  it changes.  Unfortunately, this cannot be changed.  When running from
#  the command line, however, the default is PROCESS_DPI_UNAWARE and can be
#  adjusted here.
#
try:
    log = logging.getLogger("monitor.init")
    value = 2  # PROCESS_PER_MONITOR_DPI_AWARE
    hresult = ctypes.windll.shcore.SetProcessDpiAwareness(value)
    hresult &= 0xffffffff
    if hresult == 0x80070057:  # E_INVALIDARG
        log.info("DPI awareness could not be set; "
                 "SetProcessDpiAwareness() received an invalid "
                 "argument: %d", value)
    elif hresult == 0x80070005:  # E_ACCESSDENIED
        log.info("DPI awareness could not be set; it has been set "
                 "already.")

**Comment by chuck-haatvedt** [comment] 2023-04-08 00:17
Bill,
        
        I tried your suggestion and received a 0x80070057 return code
        from the funtion which appear to be an invalid parm value...
        
        so I tried with a value of 2 and also of 0 but in both cases it
        still fails...
      
    
      
      
      
      
      
      
		@page { margin: 0.79in }
		p { margin-bottom: 0.08in }
	
      Chuck
              Haatvedt
      ***@***.***
    
    On 4/6/2023 8:02 PM, Bill Gray wrote:
    
    
      
      I've been simultaneously busy and (recently) sick.
        Hasn't left much time, I'm afraid... I've hopes of that changing
        in a bit, but appreciate the efforts of everybody else in my
        absence.
      Just based on the question about the use of 2 or -3,
        I'd suggest editing wingui/pdcscrn.c,
        going to line 2230, and changing
      
           static int ADJUST_DPI_PER_MONITOR = 2;
      
      to read
      
           static int ADJUST_DPI_PER_MONITOR = -3;
      
      and see what happens. I remain unable to replicate
        the problem and really don't know what's going on here. But if
        you try that and it suddenly works properly, I'd say we have a
        fix.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Bill-Gray/PDCursesMod/issues/280#issuecomment-1499804659",
"url": "https://github.com/Bill-Gray/PDCursesMod/issues/280#issuecomment-1499804659",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Bill-Gray** [comment] 2023-04-08 16:23
Hi @chuck-haatvedt - unless somebody has a thought as to how to make this work,  I think we should at least temporarily revert commit 012e3d90f8d47cdc3422c7178da247c548ed08dc (the one that added HiPDI support).  I am inclined to make that reversion,  update `HISTORY.md` and increment version numbers,  and post a release.  We can then re-institute HiDPI support later,  when we puzzle out why it's currently failing.

After that,  we can start tackling the backlog of push requests.   It's a nice problem to have,  in a way,  and I'm glad to see some useful fixes/feature improvements.  But between work and a bout of illness (mostly over now),  I've fallen behind a good bit. 

But the above procedure (revert a single commit,  make boilerplate changes,  release) would be quite straightforward and would provide a "stable" version.  Anyone see a reason not to just go ahead and do this?

**Comment by GitMensch** [comment] 2023-04-08 17:10
Sounds like a good approach. As this is working for some people I'd like to have an option to enable the new code via CPPFLAGS instead of a full drop.

Of course checking the PR before a release would be nice, too... maybe there are some things that are easy to review and nearly completely done?

**Comment by clangen** [comment] 2023-04-08 19:30
Hi everyone,

Sorry, real life has kept me quite busy and away from extracurriculars. It's surprising and unfortunate that this particular function/invocation is causing a crash. I know I previously mentioned something about calling convention, then walked it back, but am now starting to think it may be worth testing. If generated code is pushing arguments to the stack in the wrong order, or popping them incorrectly, we could see this sort of behavior.

If we look at the code here, in [pdcscrn.c](https://github.com/Bill-Gray/PDCursesMod/blob/ad8449a2a136d92e86032c4951c3c128ba4b52fb/wingui/pdcscrn.c#L2227), the function pointer is defined as follows:

```c
typedef HRESULT *(CDECL *set_process_dpi_awareness_t)(int);
```

However, if we look at the definition in the runtime-provided `ShellScalingApi.h`, it looks as follows:

```c
STDAPI SetProcessDpiAwareness(
    _In_ PROCESS_DPI_AWARENESS value);
```

Going further down the rabbit-hole, `STDAPI` is defined as:

```c
#define STDAPI                  EXTERN_C HRESULT STDAPICALLTYPE
```

And, `STDAPICALLTYPE` is *NOT* `__cdecl`, but rather `__stdcall`

```c
#define STDAPICALLTYPE          __stdcall
```

So, all that said, I'm curious if changing PDCurses code as follows will fix the issue for those who are having it:

```c
typedef HRESULT(STDAPICALLTYPE *SetProcessDpiAwarenessProc)(int);
                ^^^ Here: CDECL -> STDAPICALLTYPE 
````

I made the change locally and everything seems to work fine for me. I have no idea why the original didn't crash, seems like it should have... but this seems like a good change to have anyway, as it's technically more correct the the original implementation anyway.

**Comment by chuck-haatvedt** [comment] 2023-04-08 20:18
Bill,

I can confirm that the above change recommended by clangen worked for me.  

below is the code that I used...    notice the commented line and it's replacement...

    if ( shcoredll) {
        typedef HRESULT *(STDAPICALLTYPE *set_process_dpi_awareness_t)(int);
//      typedef HRESULT *(CDECL *set_process_dpi_awareness_t)(int);
        static set_process_dpi_awareness_t set_process_dpi_awareness_func;
        static int ADJUST_DPI_PER_MONITOR = 2;
        set_process_dpi_awareness_func = (set_process_dpi_awareness_t)GetProcAddress(shcoredll, "SetProcessDpiAwareness");
        if ( set_process_dpi_awareness_func) {
            set_process_dpi_awareness_func(ADJUST_DPI_PER_MONITOR);
        }
    }

**Comment by clangen** [comment] 2023-04-08 22:27
@chuck-haatvedt thank you for verifying.

@Bill-Gray, @GitMensch here's a PR with the proposed fix: https://github.com/Bill-Gray/PDCursesMod/pull/289

**Comment by GitMensch** [comment] 2023-04-10 09:26
Thank you, looks like we mostly need an adjustment to HISTORY.md to do a release (there are several commits missing in there).
Until someone finds this issue to re-occur I consider that closed-fixed now.

**Closed by GitMensch** 2023-04-10 09:26 UTC

**Comment by clangen** [comment] 2023-04-10 19:20
> Has this patch been tested for 32-bit builds? The definitions for the function types will be different on 32-bit and 64-bit builds.

I did a brief test and it seems fine for me... but I could never reproduce the original issue so it'd be great if we could have someone else verify it's working for them as well.
